### ISSUE TITLE
Bug: Price Per Ticket

### ISSUE THREAD

**Issue by WinstonNg** [awyihan0019/HCI---Assignment-Prototype#11]
Steps to reproduce
1) Sign into an account
2) Make a new booking
3) Key in every particular of the new booking
4) While at the seat page, select more than 1 seat.
5) View the particulars of the booking
6) Ticket per price is missing from the last invoice.

Expected Outcome
The price per ticket is shown to the user, along with the total ticket price and the total price of the refreshments that the user purchased.

Actual outcome
The price per ticket details are not shown to the user, only the total ticket price is shown to the user.

#Note: This bug may also apply to the Combo's (refreshments) as well, further testing will be needed in order to confirm the existence of the bug.

**Comment by wongjiahau** [comment]
Refer to ac788ae9318fcf57a4f52743a443f65378e1dda4
