### ISSUE TITLE
User able to add seats and combos without extra charges, using the edit seat and combos function.

### ISSUE THREAD

**Issue by WinstonNg** [awyihan0019/HCI---Assignment-Prototype#15]
Issue
1) The users are able to select an infinite amount of seats while editing their seatings.
2) The user can also edit their refreshment combos without incurring extra charges that should apply if the user wants to add extra refreshment combos.

Potential Solution
1a) Limit the amount of seats the user can select based on the original amount of seats they originally booked.

or

1b) Charge the users based on the extra number of seats the user has selected. The users must pay for the movie ticket's price for each of extra seats they select.

2) Charge the users the usual price for each extra refreshment combos the users add. The user must pay the original price of the combos for each combos they have added.

**Comment by awyihan0019** [comment]
Refer 4ca04dc05783c00fd1e0e0bae7f3c501c5f38525
