### ISSUE TITLE
Bugs: System Crash after new user make booking

### ISSUE THREAD

**Issue by WinstonNg** [awyihan0019/HCI---Assignment-Prototype#9]
Steps to reproduce
1) Sign up and make a new profile
2) After making a new profile, make a brand new movie booking.
3) Enter all the booking details, confirm the booking after viewing the total.
4) System crash after awhile after clicking confirm

Expected Behaviour
The system should automatically bring the user to the check booking page after the reservation is made.

Actual Behaviour
The system immediately crashed after the "Confirmed Booking" dialogbox is shown.
#Note: This bug is only present in newly created account, does not happen to hard coded user account such as Donald or Clement

**Comment by awyihan0019** [comment]
refer c8dbb188727d96620b52480fd9538d7bf4a6aa56
